### ISSUE TITLE
Consultar conferences

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-api#4]
Adicionei um registro de conferences sem vincular a um plano existente pela API, no entanto ao consultar pela aplicação o mesmo não esta sendo exibido.
OBS.: Quando repito o processo vinculando a um plano o registro é exibido.

json de criação sem o plano e domain
{
        "name": "TESTE",
        "description": "TESTE",
        
        "beginDate": "22/04/2020",
        "endDate": "23/09/2020"
  }

------
json de criação com o plano:
{
        "name": "TESTE",
        "description": "TESTE",
        "plan": {
            "id": 47,
            "name": "Planejamento Estratégico 2020",
            "structure": {
                "hasPlan": false
            },
            "domain": {}
        },
        "beginDate": "22/04/2020",
        "endDate": "23/09/2020"
  }

**Comment by nataliafvilalva** [comment]
Foi ciado o ticket PAR-61 no Jira para correção.

**Comment by nataliafvilalva** [comment]
Publicada para teste.
