### ISSUE TITLE
Falha no get locality-types

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-api#5]
Ao chamar o recurso http://201.62.46.73:1005/participe/locality-types pelo postman esta apresentando o erro descrito abaixo:

{
    "codigo": 500,
    "mensagem": "Multiple classes found in type hierarchy that map to: [Conference, LocalityType]; nested exception is org.neo4j.ogm.exception.core.AmbiguousBaseClassException: Multiple classes found in type hierarchy that map to: [Conference, LocalityType]"
}

**Comment by nataliafvilalva** [comment]
Foi ciado o ticket PAR-62 no Jira para correção.

**Comment by nataliafvilalva** [comment]
Publicada para teste.

**Comment by msantosmarcos** [comment]
Issue resolvida com sucesso.

**Comment by msantosmarcos** [comment]
resolvida
