### ISSUE TITLE
Arquivo órfão

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-api#50]
Quando é feito um upload de arquivo para a conferencia e depois ela é cancelada, a aplicação deixa o arquivo órfão no banco e no sistema de arquivos.

**Comment by vdcordeiro** [comment]
O problema foi solucionado no front end, sem qualquer modificação na api.
A solução foi efetuar os uploads e exclusões dos arquivos selecionados apenas quando o usuário pressionar o botão SAVE.

**Comment by msantosmarcos** [comment]
resolvida por Vagner
